; ESP32-S3 Nano LoRa Sensor Node — V01
;
; Trimmed deps: nano ใช้แค่ NeoPixel + LoRa (ไม่ต้องมี Ethernet/MQTT/WiFi/JSON)

[env:esp32s3_pico_nano]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM14
lib_deps =
	adafruit/Adafruit NeoPixel
	adafruit/RTClib
	adafruit/Adafruit BusIO
	sandeepmistry/LoRa
build_flags =
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DNEOPIXEL_PIN=21
board_build.flash_size = 16MB
board_build.partitions = huge_app.csv
board_build.arduino.psram_type = opi
; extra_scripts = erase_before_upload.py   ; ← ปิดไว้ก่อน
